---
title: "From Books to Movies: The "
author: Olivia DeMeo and Lilly Farah
date: May 9, 2019 at 11:55 PM
output:
  html_document:
    code_folding: hide
---

```{r, message = FALSE, echo = TRUE}

library(tidyverse)
library(ggrepel)
library(RMySQL)

db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
knitr::opts_chunk$set(connection = db, max.print = 20)

```

```{sql, output.var = "budget", message = FALSE}
SELECT title AS movie, production_year, REPLACE(SUBSTRING(info FROM 2), ',', '') AS budgetnum
FROM movie_info
RIGHT JOIN title ON movie_info.movie_id = title.id
WHERE movie_info.info_type_id = '105'
AND (movie_id = '2969942' or movie_id = '4368658' or movie_id = '4368665' or movie_id = '4368666'
or movie_id = '3518460' or movie_id = '3754229' or movie_id = '3270236' or movie_id = '4368646'
or movie_id = '4490027' or movie_id = '4436841' or movie_id = '4436842' or movie_id = '4436846' or movie_id = '4436851')
```

```{sql, output.var = "gross", message = FALSE}

SELECT title AS movie, production_year, REPLACE(REPLACE(SUBSTRING(info FROM 2 FOR 11), ',', ''), ' ', '') AS grossing
FROM movie_info
RIGHT JOIN title ON movie_info.movie_id = title.id
WHERE movie_info.info_type_id = '107'
AND (movie_id = '2969942' or movie_id = '4368658' or movie_id = '4368665' or movie_id = '4368666'
or movie_id = '3518460' or movie_id = '3754229' or movie_id = '3270236' or movie_id = '4368646'
or movie_id = '4490027' or movie_id = '4436841' or movie_id = '4436842' or movie_id = '4436846' or movie_id = '4436851')
AND (info LIKE '%(USA)' OR info LIKE '%(22 May 2016)' OR info LIKE '%(21 October 2010)' 
OR info LIKE '%(29 June 2010)' OR info LIKE '%$192,769,854%' OR info LIKE '%$281,287,133%' OR info LIKE '%(3 March 2013)')

```

```{r, message = FALSE, warning=FALSE}
budget <- budget %>% 
  mutate(budgetnum = as.numeric(budgetnum) / 1000000) %>%
  mutate(series = ifelse(grepl("Twilight", movie), "Twilight", ifelse(grepl("Hunger", movie), "The Hunger Games", "Divergent")))

gross <- mutate(gross, grossing = as.numeric(grossing) / 1000000) %>%
  mutate(series = ifelse(grepl("Twilight", movie), "Twilight", ifelse(grepl("Hunger", movie), "The Hunger Games", "Divergent")))

ggplot(budget, aes(x = production_year, y = budgetnum, label = movie)) +
  geom_point() +
  geom_smooth(color = "magenta") +
  geom_label_repel(alpha = .7, aes(color = series)) +
  labs(title = "Budget of Popular YA Series", y = "Budget (in millions)", x = "Production Year", caption = "Source: IMDb", color = "Series")

ggplot(gross, aes(x = production_year, y = grossing, label = movie)) +
  geom_point() +
  geom_smooth(color = "magenta") +
  geom_label_repel(alpha = .7, aes(color = series)) +
  labs(title = "Grossing of Popular YA Series", y = "Gross (in millions)", x = "Production Year", caption = "Source: IMDb", color = "Series")
```

